# Generated by Django 2.0.5 on 2018-05-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('surname', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('patronymic', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('work_phone', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('home_phone', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('biography', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('interests', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('photo', models.URLField()),
                ('job', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('house_number', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('flat_number', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
